config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'my-maps', to: 'maps#my_maps', as: :my_maps
  resources :maps do
    get 'compare', to: 'maps#compare', as: :compare
    resources :potential_locations, only: [:create]
    resources :point_of_interests, only: [:index, :create]
  end
  resources :point_of_interests, only: [:destroy]
  resources :potential_locations, only: [:destroy]
end

app/models/amenity.rb
class Amenity < ApplicationRecord
  belongs_to :map
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/map.rb
class Map < ApplicationRecord
  has_many :point_of_interests
  has_many :potential_locations
  has_many :amenities
  belongs_to :user

  validates :latitude, presence: { message: "Please select a location" }
  validates :longitude, presence: { message: "Please select a location" }

  def google_info
    {
      coordinates: {
        lat: latitude,
        lng: longitude
      },
      google_place_id:
    }
  end
end

app/models/point_of_interest.rb
class PointOfInterest < ApplicationRecord
  belongs_to :map
  delegate :user, to: :map

  CATEGORIES = ["Friends/Family", "Education", "Work", "Leisure", "Sports", "Other"]
  AMENITIES = ["Groceries", "Gym", "Pharmacy", "Metro", "Restaurants"]
  validates :category, inclusion: { in: CATEGORIES }
  validates :name, presence: true
  validates :address, presence: true
end

app/models/potential_location.rb
class PotentialLocation < ApplicationRecord
  belongs_to :map
  delegate :user, to: :map
  validates :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :maps
  has_many :point_of_interests, through: :maps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def show
    @map = Map.find(params[:id])
    @pot_locs = @map.potential_locations
    @pois = @map.point_of_interests
    @new_pot_loc = PotentialLocation.new

    @markers = @pot_locs.select { |pot_loc| pot_loc.latitude.present? && pot_loc.longitude.present? }.map do |pot_loc|
      {
        lat: pot_loc.latitude,
        lng: pot_loc.longitude,
        place_id: pot_loc.google_place_id,
        name: pot_loc.name,
        type: "Potential location",
        info_window_html: render_to_string(partial: "info_window", locals: { marker: pot_loc, type: "Potential Location" })
      }
    end

    @pois.each do |poi|
      @markers.push({
        place_id: poi.google_place_id,
        lat: poi.latitude,
        lng: poi.longitude,
        name: poi.name,
        type: "Point of Interest",
        info_window_html: render_to_string(partial: "info_window", locals: { marker: poi, type: "Point of Interest" })
      })
    end

    @point_of_interests_ids = @map.point_of_interests.map(&:google_place_id)
  end

  def my_maps
    @maps = current_user.maps
    @map = Map.new # Initialize a new Map object
    @address = @map.city
  end


  def compare
    @map = Map.find(params[:map_id])
    @pot_locs = PotentialLocation.where(map: @map)
    @pois = PointOfInterest.where(map: @map)
    @potentialLocations = @pot_locs.select { |pot_loc| pot_loc.latitude.present? && pot_loc.longitude.present? }.map do |pot_loc|
      {
        lat: pot_loc.latitude,
        lng: pot_loc.longitude,
        place_id: pot_loc.google_place_id,
        name: pot_loc.name,
        id: pot_loc.id
      }
    end
    @pointOfInterests = @pois.select { |poi| poi.latitude.present? && poi.longitude.present? }.map do |poi|
      {
        lat: poi.latitude,
        lng: poi.longitude,
        place_id: poi.google_place_id,
        name: poi.name,
        id: poi.id
      }
    end
    # raise
  end

  def create
    @map = Map.new(map_params)
    @map.user = current_user

    if @map.save
      redirect_to map_path(@map), notice: "Map was successfully created."
    else
      @maps = current_user.maps
      flash[:alert] = "Please select a location"
      redirect_to action: :my_maps
    end
  end

  def destroy
    @map = Map.find(params[:id])
    @map.destroy
    redirect_to my_maps_path, notice: "Potential Location was successfully removed."
  end

  private

  def set_map
    @map = Map.find(params[:id])
  end

  def map_params
    params.require(:map).permit(:city, :latitude, :longitude, :google_place_id)
  end

  def pot_locs_params
    params.require(:potential_location).permit(:name, :adress)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @disable_footer = true
  end

end

app/controllers/point_of_interests_controller.rb
class PointOfInterestsController < ApplicationController
  before_action :set_map, except: :destroy

  def index
    @point_of_interests = @map.point_of_interests
    @poi = PointOfInterest.new
  end

  def create
    @poi = PointOfInterest.new(poi_params)
    @map = Map.find(params[:map_id])
    @poi.map = @map
    if @poi.save
      redirect_to map_point_of_interests_path, notice: "Point of Interest was successfully added."
    else
      @point_of_interests = @map.point_of_interests
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @poi = PointOfInterest.find(params[:id])
    @poi.destroy
    redirect_to map_point_of_interests_path(@poi.map), notice: "Point of Interest was successfully removed."
  end

  private

  def set_map
    @map = Map.find(params[:map_id])
  end

  def poi_params
    params.require(:point_of_interest).permit(:name, :address, :category, :latitude, :longitude, :google_place_id)
  end


end

app/controllers/potential_locations_controller.rb
class PotentialLocationsController < ApplicationController

  def create
    @map = Map.find(params[:map_id])
    @new_pot_loc = PotentialLocation.new(pot_locs_params)
    @pot_locs = @map.potential_locations
    @new_pot_loc.map = @map
    if @new_pot_loc.save
      redirect_to map_path(@map), notice: "Potential Location was successfully created."
    else
      render 'maps/show', status: :unprocessable_entity
    end

  end

  def destroy
    @pot_loc = PotentialLocation.find(params[:id])
    @pot_loc.destroy
    redirect_to map_path, notice: "Potential Location was successfully removed."
  end

  private

  def pot_locs_params
    params.require(:potential_location).permit(:address, :latitude, :longitude, :google_place_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tag_helper.rb
module MetaTagHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>mApt</title>
      <%= favicon_link_tag "favicon.png", rel: "icon", type: "image/png" %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>">
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:image" content="<%= meta_image %>">
    <meta property="og:description" content="<%= meta_description %>">
    <meta property="og:site_name" content="<%= meta_title %>">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
      <div id="main-container">
    <%= render "shared/flashes" %>
      <%= render "shared/navbar" %>
      <%= yield %>
      </div>
    <%= render "shared/footer" unless @disable_footer %>
  </body>
</html>

app/views/maps/_info_window.html.erb
<div class="card-window bg-light">

    <h6><%= type %></h6>

  <p class="text-secondary">
    Name : <%= marker[:name] %>
  </p>
  <p class="text-secondary">
    Address : <%= marker[:address] %>
  </p>
</div>

app/views/maps/compare.html.erb
<div class="score-div"
  data-controller="compare"
  data-compare-potential-locations-value="<%= @potentialLocations.to_json %>"
  data-compare-map-id-value="<%= @map.id %>"
  data-compare-point-of-interests-value="<%= @pointOfInterests.to_json %>"
  data-action="DOMContentLoaded->compare#matrix">

  <p> <i class="fa-solid fa-arrow-left"></i> <%= link_to "Go back to #{@map.city}", map_path(@map.id), class: "text-decoration-none" %></p>
  <h1 class="text-center"><strong>Compare Scores for <%= @map.city %></strong></h1>

 <div class="transportation-btn-div">
    <button class="btn-active"
            data-travel-mode="walking"
            data-action="click->compare#getScores"
            data-compare-target="buttons">
        <div class="">
          <i class="fa-solid fa-person-walking fa-lg"></i>
        </div>
          <div>
            <p class="distance-name"> Walking</p>
          </div>
    </button>

    <button class="btn-distances"
            data-travel-mode="cycling"
            data-action="click->compare#getScores"
            data-compare-target="buttons">
      <div class="">
        <i class="fa-solid fa-bicycle fa-lg"></i>
      </div>
      <div>
        <p class="distance-name">Cycling</p>
      </div>
    </button>


    <button class="btn-distances"
            data-travel-mode="bus"
            data-action="click->compare#getScores"
            data-compare-target="buttons">
      <i class="fa-solid fa-bus fa-lg"></i>
      <div>
        <p class="distance-name">Public Transit</p>
      </div>
    </button>

    <button class="btn-distances"
            data-travel-mode="driving"
            data-action="click->compare#getScores"
            data-compare-target="buttons">
      <div class="">
        <i class="fa-solid fa-car fa-lg"></i>
      </div>
        <div>
          <p class="distance-name">Driving</p>
        </div>
    </button>
  </div>

  <% @pot_locs.each do |loc| %>
    <div
      class="adress-card-dropdown"
      data-card-id="<%= loc.id %>"
      data-compare-target="card">

      <div class="adress-card">
        <%= loc.address %>
        <p class="score" ></p>
      </div>

      <%# <a data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        <i class="fa-solid fa-angle-down" style="color: #bdbdbd;">
      </a> %>
            <div class="poi-grid">
              <% @pois.each do |poi| %>
              <div data-poi-id="<%= poi.id %>">
                  <div class="">
                    <h5 class="poi_name"><%= poi.name %></h5>
                    <div class="poi-icons">
                      <i class="fa-regular fa-compass"></i>
                      <h6 class="distance"></h6>
                    </div>
                    <div class="poi-icons">
                      <i class="fa-regular fa-clock"></i>
                      <h6 class="time"></h6>
                    </div>
                  </div>
              </div>
              <% end %>
            </div>
    </div>
  <% end %>
</div>

<%# THIS SCRIPT BELOW IS TEMPORARILY PLACED IN SHOW.HTML.ERB - DO NOT DELETE %>
<script>
  (g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})({
    key: "<%= ENV['GOOGLE_API'] %>",
    v: "weekly",
    // Use the 'v' parameter to indicate the version to use (weekly, beta, alpha, etc.).
    // Add other bootstrap parameters as needed, using camel case.
  });
</script>

app/views/maps/my_maps.html.erb
<div class="card-category-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path("GPS.jpg") %>)">

    <h1 class="title">My Cities</h1>
    <%= simple_form_for(@map, html: { data: { controller: 'autocomplete', autocomplete_filter_value: 'city' } }) do |f| %>
    <div class="city-form">
          <%= f.input :city, label: false, input_html: { data: { autocomplete_target: 'searchField' } } %>
          <%= f.submit "Add a city", class: "btn-add-city" %>
          <%= render 'shared/form_hidden_google_info', f: %>
    </div>
  <% end %>
</div>

<% if flash.now[:alert] %>
<% end %>




<div class="card-list">
  <% @maps.each do |map| %>
    <%= link_to map_path(map.id) do %>
      <div class="card-item">
            <% unsplash_photo = Unsplash::Photo.search(map.city).first %>
            <% if unsplash_photo %>
              <div class="image-container" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= unsplash_photo.urls.regular %>');">
                <div class="overlay-content">
                  <div class="centered-content">
                    <div class="title"><p><%= map.city.titleize %></p></div>
                  </div>
                </div>
              </div>
            <% else %>
              <p>No image found for <%= map.city %></p>
            <% end %>
      </div>
    <% end %>
  <% end %>
</div>




<%# THIS SCRIPT BELOW IS TEMPORARILY PLACED IN SHOW.HTML.ERB - DO NOT DELETE %>
<script>
    (g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})({
    key: "<%= ENV['GOOGLE_API'] %>",
    v: "weekly",
    // Use the 'v' parameter to indicate the version to use (weekly, beta, alpha, etc.).
    // Add other bootstrap parameters as needed, using camel case.
  });


</script>

app/views/maps/new.html.erb
<%= simple_form_for(@map) do |f| %>
  <%# <%= f.error_notification %>
  <%# <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %> %> %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :city %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/maps/show.html.erb
<div class="whole-page">
  <div class="header-div">



      <h1><strong><%= @map.city %></strong></h1>



    <%# create a logic to display city name that was created %>
      <%= simple_form_for([@map, @new_pot_loc], html: { data: { controller: 'autocomplete' } }) do |f| %>
        <div class="header-search">
          <div class="form-inputs">
            <%= f.input :address, label: false, input_html: { data: { autocomplete_target: 'searchField' }, placeholder: "Where are you thinking of moving?", class: "search-input-map" }%>
          </div>
          <%= render 'shared/form_hidden_google_info', f: %>
          <div class="form-actions">
            <%= f.button :submit, class: "search-button-map" %>
          </div>
        </div>
      <% end %>

      <button class="btn-options" onclick="window.location.href='/maps/<%= @map.id %>/point_of_interests';">Points of Interest</button>
      <button class="btn-options" onclick="window.location.href='/maps/<%= @map.id %>/compare';">Compare Scores</button>

  </div>

    <div class="pol-div">
      <% @pot_locs.each do |loc| %>
        <div class="adress-div">
          <%= loc.address %>
          <div class ="delete-pol">
            <%= link_to potential_location_path(loc), data: {turbo_method: :delete, turbo_confirm: "Delete #{loc.address}?"} do %>
              <i class="fa-solid fa-x fa-2xs" style="color: #c9c9c9;"></i>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>



  <div class="map-toggle">
    <div
      id="map"
      data-controller="map"
      data-map-city-info-value="<%= @map.google_info.to_json %>"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-poi-ids-value="<%= @point_of_interests_ids.to_json %>"
      data-map-target="content"
      >
  </div>

  <div class="legend-cards">
    <div class="legend-card">
      <div class="legend-color-poi"></div>
      <p class="text-secondary fw-bold">Potential Locations</p>
    </div>
    <div class="legend-card">
      <div class="legend-color-pol"></div>
      <p class="text-secondary fw-bold">Points of Interest</p>
    </div>
  </div>


<%# THIS SCRIPT BELOW IS TEMPORARILY PLACED IN SHOW.HTML.ERB - DO NOT DELETE %>
<script>
  (g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})({
    key: "<%= ENV['GOOGLE_API'] %>",
    v: "weekly",
    // Use the 'v' parameter to indicate the version to use (weekly, beta, alpha, etc.).
    // Add other bootstrap parameters as needed, using camel case.
  });
</script>

app/views/pages/home.html.erb
<div class="landing-image">
  <%= image_tag("landing.jpg", height: '550', width: '100%') %>
  <div class="overlay"></div>
  <h1 class="title">Find the best location for your next home.</h1>
  <button class="btn-get-started" onclick="window.location.href='/my-maps';">Get Started</button>
</div>



<div class="card-product">
  <div class="card-info">
    <%= image_tag("home-button.png", height: '100', width: '100', class: 'mb-3') %>
    <p>Discover the amenities nearby your potential home address</p>
  </div>
  <div class="card-info">
    <%= image_tag("pin.png", height: '100', width: '100', class: 'mb-3') %>
    <p>Save the addresses that matter the most for you!</p>
  </div>
  <div class="card-info">
    <%= image_tag("gps.png", height: '100', width: '100', class: 'mb-3') %>
    <p>See and compare distances all in one place</p>
  </div>
</div>

app/views/point_of_interests/index.html.erb
<div class="score-div">
  <p class="mt-5"><i class="fa-solid fa-arrow-left"></i> <%= link_to "Go back to #{@map.city}", map_path(@map.id), class: "text-decoration-none" %></p>

<h1 class="text-center"><strong><%= @map.city %>'s Points of Interest</strong></h1>
</div>


<div class="container-address-book">
  <div>
    <%= simple_form_for([@map, @poi], html: { data: { controller: 'autocomplete' } }) do |f| %>
    <div>
      <div class="form-inputs">

        <%= f.input :name, placeholder: "Tom's House" %>
        <%= f.input :address, placeholder: "2543 Rosemont St", label: false, input_html: { data: { autocomplete_target: 'searchField' } }%>

        <%= f.input :category, collection: ["Friends/Family", "Education", "Work", "Leisure", "Sports", "Other"]   %>
        <%= render 'shared/form_hidden_google_info', f: %>

      </div>

      <div class="form-actions">
        <%= f.button:submit, "Add Point of Interest", class: "btn-options" %>
      </div>
    </div>
    <% end %>
  </div>


  <div>
    <% if current_user.maps.any? %>
        <% @point_of_interests.each do |poi| %>
          <div class="card-poi">
            <div class="poi-white">
              <div>
                <p><%= poi.name.titleize %></p>
                <p class="poi-black"><%= poi.category.titleize %></p>
              </div>
                  <div class="poi-garbage" >
                  <%= link_to point_of_interest_path(poi), data: {turbo_method: :delete, turbo_confirm: "Delete #{poi.name}?"} do %>
                      <i class="fa-solid fa-trash-can" style="color: #11009e;"></i>
                  <% end %>
              </div>
            </div>
             <div class="poi-purple">
               <p><%= poi.address.titleize %></p>
             </div>
          </div>
        <% end %>
    <% else %>
      <p>You have no maps</p>
    <% end %>
  </div>
</div>

<script>
  (g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})({
    key: "<%= ENV['GOOGLE_API'] %>",
    v: "weekly",
    // Use the 'v' parameter to indicate the version to use (weekly, beta, alpha, etc.).
    // Add other bootstrap parameters as needed, using camel case.
  });

</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="/my-maps"><i class="fa-solid fa-map-location-dot" style="color: #bfbebe;"></i></a>
  </div>
  <div class="footer-copyright">
    Your lifestyle, without compromise.
  </div>
</div>

app/views/shared/_form_hidden_google_info.html.erb
<div>
  <%= f.input :latitude, label: false, as: :hidden, input_html: { data: { autocomplete_target: 'latitude' } } %>
  <%= f.input :longitude, label: false, as: :hidden, input_html: { data: { autocomplete_target: 'longitude' } } %>
  <%= f.input :google_place_id, label: false, as: :hidden, input_html: { data: { autocomplete_target: 'googlePlaceId' } } %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-mapt">
  <div class="container-fluid">
    <div class="navbar-img">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag("logo.png")%>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item">
          <div class="links d-flex flex-row">
          <div class="p-2">
            <%= link_to "My Cities", my_maps_path, class: "nav-link" %>
          </div>
          </li>
          <li class="nav-item">
          <div class="p-2">
            <%# link_to "My Address Book", point_of_interests_path, class: "nav-link" %>
          </div>
          </li>
        </ul>
      <% end %>

      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/louisrivest", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>